import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

/**
 * NASA OMNI2 hourly near-Earth solar wind, averaged to one dynamic-pressure
 * sample per UTC day. Flow pressure is word 29 (fill 99.99 nPa).
 * https://spdf.gsfc.nasa.gov/pub/data/omni/low_res_omni/omni2.text
 */
const BASE_URL = 'https://spdf.gsfc.nasa.gov/pub/data/omni/low_res_omni'
const OUTPUT = resolve('src/data/generated/solarWind.ts')
const PRESSURE_FILL = 99.99
const MS_PER_DAY = 86_400_000

function yearsToFetch(now = new Date()): number[] {
  const year = now.getUTCFullYear()
  return [year - 2, year - 1, year]
}

function parseHour(line: string): { dayMs: number; pdyn: number } | null {
  const parts = line.trim().split(/\s+/)
  if (parts.length < 29) return null
  const year = Number(parts[0])
  const doy = Number(parts[1])
  const pdyn = Number(parts[28])
  if (!Number.isFinite(year) || !Number.isFinite(doy) || !Number.isFinite(pdyn)) return null
  if (!(pdyn > 0) || pdyn >= PRESSURE_FILL) return null
  const dayMs = Date.UTC(year, 0, doy)
  return { dayMs, pdyn }
}

async function fetchYear(year: number): Promise<string> {
  const url = `${BASE_URL}/omni2_${year}.dat`
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`${url} → ${response.status} ${response.statusText}`)
  }
  return response.text()
}

function dailyMeans(text: string): Map<number, number> {
  const sums = new Map<number, { sum: number; n: number }>()
  for (const line of text.split(/\n/)) {
    if (!line.trim()) continue
    const row = parseHour(line)
    if (!row) continue
    const bucket = sums.get(row.dayMs) ?? { sum: 0, n: 0 }
    bucket.sum += row.pdyn
    bucket.n += 1
    sums.set(row.dayMs, bucket)
  }
  const means = new Map<number, number>()
  for (const [dayMs, { sum, n }] of sums) {
    means.set(dayMs, Math.round((sum / n) * 100) / 100)
  }
  return means
}

function pack(means: Map<number, number>): { startMs: number; pdynNPa: number[] } {
  const days = [...means.keys()].sort((a, b) => a - b)
  if (days.length === 0) throw new Error('No OMNI dynamic-pressure samples')
  const startMs = days[0]
  const lastMs = days[days.length - 1]
  const count = Math.round((lastMs - startMs) / MS_PER_DAY) + 1
  const pdynNPa = Array.from({ length: count }, () => 0)
  for (const dayMs of days) {
    const index = Math.round((dayMs - startMs) / MS_PER_DAY)
    pdynNPa[index] = means.get(dayMs) ?? 0
  }
  return { startMs, pdynNPa }
}

const years = yearsToFetch()
const means = new Map<number, number>()
for (const year of years) {
  const text = await fetchYear(year)
  for (const [dayMs, pdyn] of dailyMeans(text)) means.set(dayMs, pdyn)
}
const { startMs, pdynNPa } = pack(means)
const filled = pdynNPa.filter((p) => p > 0).length

await mkdir(dirname(OUTPUT), { recursive: true })
const body = `/**
 * Generated by scripts/generate-solar-wind.ts from NASA OMNI2 hourly files
 * (${years.join(', ')}), averaged to UTC days. Zero is a missing day.
 * Do not edit by hand.
 */
export const SOLAR_WIND_START_MS = ${startMs}
export const SOLAR_WIND_PDYN_NPA: readonly number[] = ${JSON.stringify(pdynNPa)}
`
await writeFile(OUTPUT, body)
console.log(
  `generate-solar-wind: ${filled} of ${pdynNPa.length} days from ${new Date(startMs).toISOString().slice(0, 10)}`,
)
